version: '3.8'

services:
  erazershop.web.public:
    build:
      context: .
      dockerfile: dockerfile.public
    ports:
      - "4000:4000"
  erazershop.web.admin:
    build:
      context: .
      dockerfile: dockerfile.admin
    ports:
      - "4001:4001"
